# /backend/migrations/versions/21213ef0877d_add_is_breaking_news_to_article_model.py

"""Add is_breaking_news to Article model

Revision ID: 21213ef0877d
Revises: 
Create Date: 2025-09-14 00:10:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21213ef0877d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - CORRECTED ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_breaking_news', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - CORRECTED ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('is_breaking_news')
    # ### end Alembic commands ###