"""Add created_at and updated_at to Article

Revision ID: c5ac2e991ea9
Revises: 8e56e99016f7
Create Date: 2025-09-14 02:33:54.353401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ac2e991ea9'
down_revision = '8e56e99016f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_index(batch_op.f('idx_article_content_fts'), postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_article_content_fts'), [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || content)")], unique=False, postgresql_using='gin')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
