# /.github/workflows/breaking_news_job.yml

name: Breaking News Generation

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-breaking-news-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Create Firebase Credentials File
      run: echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > backend/firebase-credentials.json

    - name: Create Firebase Credentials File
      run: echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > backend/firebase-credentials.json


    # --- NEW: A step to safely debug your secrets ---
    - name: Debug Secrets
      run: |
        echo "Firebase secret is present: ${{ secrets.FIREBASE_CREDENTIALS_JSON != '' }}"
        echo "Groq secret is present: ${{ secrets.GROQ_API_KEY != '' }}"

    - name: Run Breaking News Worker
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        GENERATION_API_URL: ${{ secrets.GENERATION_API_URL }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      run: python backend/breaking_news_worker.py