# /.github/workflows/future_content_job.yml

name: Future-Proof Content Generation

on:
  schedule:
    # This CRON string means "run at 5 AM UTC every Sunday".
    - cron: '0 5 * * 0'
  workflow_dispatch:

jobs:
  run-future-content-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Create Firebase Credentials File
      run: echo "${{ secrets.FIREBASE_CREDENTIALS_JSON }}" > backend/firebase-credentials.json

    - name: Run Future Content Worker
      env:
        # This script needs the same secrets as your other workers
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        FIREWORKS_API_KEY: ${{ secrets.FIREWORKS_API_KEY }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        GENERATION_API_URL: ${{ secrets.GENERATION_API_URL }}
      run: python backend/future_content_worker.py