name: Weekly Content Cluster Generation

on:
  schedule:
    - cron: '0 2 * * 1' # Runs once a week on Monday at 2 AM UTC
  workflow_dispatch:

jobs:
  build-and-run-weekly-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    # --- NEW STEP: Install Pandoc and LaTeX ---
    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create Firebase Credentials File
      run: echo '${{ secrets.FIREBASE_CREDENTIALS_JSON }}' > firebase-credentials.json

    - name: Run Weekly Content Worker
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        GROQ_API_KEY: ${{ secrets.GROQ_APISEC_KEY }}
        GENERATION_API_URL: ${{ secrets.GENERATION_API_URL }}
        # --- NEW SECRET ---
        GUMROAD_ACCESS_TOKEN: ${{ secrets.GUMROAD_ACCESS_TOKEN }}
      run: python weekly_content_worker.py
    
    - name: Commit and push updated files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        # --- UPDATE THIS LINE to include new files ---
        git add weekly_plan.json *.md *.pdf *.log
        git diff --staged --quiet || git commit -m "Update weekly content plan and compiled assets"
        git push